### ISSUE TITLE
Randoop throws AssertionError for a math package

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mernst/randoop#44]
```
What steps will reproduce the problem?
1. Download the org.apache.commons.math3 package
2. Test the package (a list with all package classes provided with the 
--classlist parameter)
3. Observe Randoop exiting with an assertion error

What is the expected output? What do you see instead?

The expected output should be without exceptions, resulting in Randoop writing 
generated unit tests to the file system.

Instead I get the following:

Creating Junit tests (2236 tests)...Throwable thrown while handling 
command:java.lang.AssertionError
java.lang.AssertionError
        at randoop.main.GenTests.handle(GenTests.java:529)
        at randoop.main.Main.nonStaticMain(Main.java:80)
        at randoop.main.Main.main(Main.java:42)
Randoop failed.
Last sequence under execution:var0 =  prim : int:1079574528 : 
var1 =  prim : boolean:true : 
var2 =  cons : 
org.apache.commons.math3.stat.regression.MillerUpdatingRegression.<init>(int,boo
lean) : var0 var1

What version of the product are you using? On what operating system?

Randoop 1.3.3. The operating system is GNU/Linux Trisquel 6.0.

Please provide any additional information below.

This is the command that I used to run Randoop:

java $JVM_FLAGS -ea -cp lib/randoop.jar:lib/junit4.jar:../src/ 
randoop.main.Main gentests --classlist=classlist.txt 
--junit-output-dir=tests-round-1/ --junit-classname=Randoop1Test --timelimit=60 
--forbid-null=false --small-tests=true --testsperfile=1

File classlist.txt is attached.

```

Original issue reported on code.google.com by `ma...@cs.utah.edu` on 16 Nov 2013 at 4:34

Attachments:
* [classlist.txt](https://storage.googleapis.com/google-code-attachments/randoop/issue-44/comment-0/classlist.txt)

**Comment by mernst** [comment]
I cannot reproduce the problem.  Maybe it has already been fixed.

Here are the exact commands that I ran:

cd ~/tmp
wget http://mirrors.nxnethosting.com/apache//commons/math/binaries/commons-math3-3.5-bin.tar.gz
tar xzf commons-math3-3.5-bin.tar.gz
java -ea -cp $randoop/dist/randoop.jar:commons-math3-3.5/commons-math3-3.5.jar randoop.main.Main gentests --classlist=classlist.txt --junit-output-dir=tests-round-1/ --junit-classname=Randoop1Test --timelimit=60 --forbid-null=false --small-tests=true --testsperfile=1
